ALTER TABLE cal_juez ALTER COLUMN j1 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j2 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j3 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j4 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j5 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j6 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j7 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j8 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j9 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j10 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j11 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN j12 VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN divepoints VARCHAR(20);
ALTER TABLE cal_juez ALTER COLUMN totalpoints VARCHAR(20);


ALTER TABLE cal_participante ALTER COLUMN calificacion  VARCHAR(20);